edition = "2018"
enum_discrim_align_threshold = 40
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
preserve_block_start_blank_lines = true
overflow_delimited_expr = true
struct_field_align_threshold = 40
#field_init_shorthand = true
wrap_comments = true
